security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        auth:
            pattern: ^/auth
            stateless: true
            json_login:
                check_path: auth_login
                username_path: email
                password_path: password

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\SessionAuthenticator
            stateless: true  # API sin estado (no guarda sesiones en el servidor)

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_MANAGER: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_MANAGER]
        ROLE_AI_ASSISTANT: []

    access_control:
        - { path: ^/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/auth/logout, roles: IS_AUTHENTICATED_FULLY }

        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
