controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /
    controller: App\Controller\AuthController::index
    methods: [GET]
    options:
        isPublic: true
login:
    path: /auth/login
    controller: App\Controller\AuthController::login
    methods: [POST]
    options:
        isPublic: true
logout:
    path: /api/auth/logout
    controller: App\Controller\AuthController::logout
    methods: [POST]
    options:
        isPublic: false
register:
    path: /auth/register
    controller: App\Controller\AuthController::register
    methods: [POST]
    options:
        isPublic: true
