controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /
    controller: App\Controller\AuthController::index
    methods: [GET]
    options:
        isPublic: true
login:
    path: /auth/login
    controller: App\Controller\AuthController::login
    methods: [POST]
    options:
        isPublic: true
register:
    path: /auth/register
    controller: App\Controller\AuthController::register
    methods: [POST]
    options:
        isPublic: true
logout:
    path: /api/auth/logout
    controller: App\Controller\AuthController::logout
    methods: [POST]
    options:
        isPublic: false
tasks_index:
    path: /api/tasks
    controller: App\Controller\TaskController::index
    methods: [GET]
    options:
        isPublic: false
    requirements:
        _format: json
tasks_create:
    path: /api/tasks
    controller: App\Controller\TaskController::create
    methods: [POST]
    options:
        isPublic: false
    requirements:
        _format: json

tasks_update:
    path: /api/tasks/{id}
    controller: App\Controller\TaskController::update
    methods: [PUT, PATCH]
    options:
        isPublic: false
    requirements:
        _format: json

tasks_delete:
    path: /api/tasks/{id}
    controller: App\Controller\TaskController::delete
    methods: [DELETE]
    options:
        isPublic: false
    requirements:
        _format: json

