parameters:

services:
    # Configuración predeterminada para todos los servicios en este archivo
    _defaults:
        autowire: true      # Inyecta dependencias automáticamente
        autoconfigure: true # Registra automáticamente comandos, eventos, suscriptores, etc.

    # Hace que las clases dentro de src/ estén disponibles como servicios
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Registro explícito del ExceptionListener en caso de que Symfony no lo detecte automáticamente
    App\EventListener\ExceptionListener:
        arguments:
            $env: '%kernel.environment%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 50 }
